In [4]:
import numpy as np
import pandas as pd 
import warnings
warnings.filterwarnings ('ignore')
import glob

In [5]:
path = 'C://Users//suayp//Desktop//AI//pokemon'
filenames = glob.glob(path + "/*.csv")
pokemon = pd.DataFrame()
for f in filenames:
    df = pd.read_csv(f)
    pokemon = pokemon.append(df, ignore_index = True, sort = True)

In [6]:
pokemon.head(10)

#  Attack  Defense  Generation  HP  Legendary                       Name  \
0  1      49       49           1  45      False                  Bulbasaur   
1  2      62       63           1  60      False                    Ivysaur   
2  3      82       83           1  80      False                   Venusaur   
3  3     100      123           1  80      False      VenusaurMega Venusaur   
4  4      52       43           1  39      False                 Charmander   
5  5      64       58           1  58      False                 Charmeleon   
6  6      84       78           1  78      False                  Charizard   
7  6     130      111           1  78      False  CharizardMega Charizard X   
8  6     104       78           1  78      False  CharizardMega Charizard Y   
9  7      48       65           1  44      False                   Squirtle   

   Sp. Atk  Sp. Def  Speed  Total Type 1  Type 2  
0       65       65     45    367  Grass  Poison  
1       80       80     60    467  Grass  Poison  
2      100      100     80    607  Grass  Poison  
3      122      120     80    725  Grass  Poison  
4       60       50     65    335   Fire     NaN  
5       80       65     80    447   Fire     NaN  
6      109       85    100    596   Fire  Flying  
7      130       85    100    742   Fire  Dragon  
8      159      115    100    716   Fire  Flying  
9       50       64     43    363  Water     NaN

In [7]:
pokemon.tail(10)

#  Attack  Defense  Generation   HP  Legendary                 Name  \
790  714      30       35           6   40      False               Noibat   
791  715      70       80           6   85      False              Noivern   
792  716     131       95           6  126       True              Xerneas   
793  717     131       95           6  126       True              Yveltal   
794  718     100      121           6  108       True     Zygarde50% Forme   
795  719     100      150           6   50       True              Diancie   
796  719     160      110           6   50       True  DiancieMega Diancie   
797  720     110       60           6   80       True  HoopaHoopa Confined   
798  720     160       60           6   80       True   HoopaHoopa Unbound   
799  721     110      120           6   80       True            Volcanion   

     Sp. Atk  Sp. Def  Speed  Total   Type 1  Type 2  
790       45       40     55    260   Flying  Dragon  
791       97       80    123    567   Flying  Dragon  
792      131       98     99    838    Fairy     NaN  
793      131       98     99    838     Dark  Flying  
794       81       95     95    713   Dragon  Ground  
795      100      150     50    700     Rock   Fairy  
796      160      110    110    800     Rock   Fairy  
797      150      130     70    720  Psychic   Ghost  
798      170      130     80    840  Psychic    Dark  
799      130       90     70    720     Fire   Water

In [9]:
pokemon['Name'].unique()

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard',
       'CharizardMega Charizard X', 'CharizardMega Charizard Y',
       'Squirtle', 'Wartortle', 'Blastoise', 'BlastoiseMega Blastoise',
       'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna',
       'Beedrill', 'BeedrillMega Beedrill', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'PidgeotMega Pidgeot', 'Rattata', 'Raticate', 'Spearow',
       'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew',
       'Sandslash', 'Nidoran♀', 'Nidorina', 'Nidoqueen', 'Nidoran♂',
       'Nidorino', 'Nidoking', 'Clefairy', 'Clefable', 'Vulpix',
       'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat',
       'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat',
       'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
       'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine',
       'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra',

In [10]:
pokemon['Name'].nunique()

800

In [11]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           800 non-null    int64 
 1   Attack      800 non-null    int64 
 2   Defense     800 non-null    int64 
 3   Generation  800 non-null    int64 
 4   HP          800 non-null    int64 
 5   Legendary   800 non-null    bool  
 6   Name        800 non-null    object
 7   Sp. Atk     800 non-null    int64 
 8   Sp. Def     800 non-null    int64 
 9   Speed       800 non-null    int64 
 10  Total       800 non-null    int64 
 11  Type 1      800 non-null    object
 12  Type 2      414 non-null    object
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB


In [12]:
df1 = covid[['Name', 'Attack', 'Defense']]
df1.head(10)

Name  Attack  Defense
0                  Bulbasaur      49       49
1                    Ivysaur      62       63
2                   Venusaur      82       83
3      VenusaurMega Venusaur     100      123
4                 Charmander      52       43
5                 Charmeleon      64       58
6                  Charizard      84       78
7  CharizardMega Charizard X     130      111
8  CharizardMega Charizard Y     104       78
9                   Squirtle      48       65

In [13]:
df1.iloc[1:4]

Name  Attack  Defense
1                Ivysaur      62       63
2               Venusaur      82       83
3  VenusaurMega Venusaur     100      123

In [15]:
    df1.loc[df1['Name'] == 'Bulbasaur']

Name  Attack  Defense
0  Bulbasaur      49       49

In [18]:
display('Sorted Data Frame', df1.sort_values(['Name'], ascending = True).head(10))

'Sorted Data Frame'

Name  Attack  Defense
510                  Abomasnow      92       75
511    AbomasnowMega Abomasnow     132      105
68                        Abra      20       15
392                      Absol     130       60
393            AbsolMega Absol     150       60
678                   Accelgor      70       40
750       AegislashBlade Forme     150       50
751      AegislashShield Forme      50      150
153                 Aerodactyl     105       65
154  AerodactylMega Aerodactyl     135       85

In [20]:
for index, row in df1.iterrows():
    if(row['Name'] == 'Abra'):
        display(row[['Name', 'Attack']])

Name      Abra
Attack      20
Name: 68, dtype: object

In [21]:
pokemon['Name'].drop_duplicates(keep = 'first').head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

DIGER_ODEV

In [22]:
import numpy as np

In [36]:
x = np.random.randint(0, 10, (3, 3))
print(x)

[[4 7 9]
 [2 1 8]
 [1 7 0]]


In [47]:
x_kerekok = np.power(x, 2)
print("x kerekok:\n", x_kerekok)

x kerekok:
 [[16 49 81]
 [ 4  1 64]
 [ 1 49  0]]


In [38]:
x_kup = np.power(x, 3)
print("x kup:\n", x_kup)

x kup:
 [[ 64 343 729]
 [  8   1 512]
 [  1 343   0]]


In [39]:
sin_x = np.sin(x)
print("sin x:\n", sin_x)

sin x:
 [[-0.7568025   0.6569866   0.41211849]
 [ 0.90929743  0.84147098  0.98935825]
 [ 0.84147098  0.6569866   0.        ]]


In [40]:
cos_x = np.cos(x)
print("cos_x:\n", cos_x)

cos_x:
 [[-0.65364362  0.75390225 -0.91113026]
 [-0.41614684  0.54030231 -0.14550003]
 [ 0.54030231  0.75390225  1.        ]]


In [41]:
tan_x = np.tan(x)
print("tan_x:\n", tan_x)

tan_x:
 [[ 1.15782128  0.87144798 -0.45231566]
 [-2.18503986  1.55740772 -6.79971146]
 [ 1.55740772  0.87144798  0.        ]]


In [42]:
sinh_x = np.sinh(x)
print("sinh_x:\n", sinh_x)

sinh_x:
 [[2.72899172e+01 5.48316123e+02 4.05154190e+03]
 [3.62686041e+00 1.17520119e+00 1.49047883e+03]
 [1.17520119e+00 5.48316123e+02 0.00000000e+00]]


In [43]:
cosh_x = np.cosh(x)
print("cosh_x:\n", cosh_x)


cosh_x:
 [[2.73082328e+01 5.48317035e+02 4.05154203e+03]
 [3.76219569e+00 1.54308063e+00 1.49047916e+03]
 [1.54308063e+00 5.48317035e+02 1.00000000e+00]]


In [45]:
exp_x = np.exp(x)
print("exp_x:\n", exp_x)

exp_x:
 [[5.45981500e+01 1.09663316e+03 8.10308393e+03]
 [7.38905610e+00 2.71828183e+00 2.98095799e+03]
 [2.71828183e+00 1.09663316e+03 1.00000000e+00]]


In [46]:
tanh_x = np.tanh(x)
print("tanh_x:\n", tanh_x)

tanh_x:
 [[0.9993293  0.99999834 0.99999997]
 [0.96402758 0.76159416 0.99999977]
 [0.76159416 0.99999834 0.        ]]
